services:
  backend:
    image: ${BACKEND_IMAGE:-ncafe-backend:latest}
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yj-dev-backend
    ports:
      - "8065:8081"
    volumes:
      - ./upload:/app/upload
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://db:5432/ncafedb}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    image: ${FRONTEND_IMAGE:-ncafe-frontend:latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: yj-dev-frontend
    ports:
      - "3065:3001"
    environment:
      - API_BASE_URL=http://backend:8081
      - SESSION_SECRET=${SESSION_SECRET:-ea78b9775aeded53fdf6ae11a3219db6}
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:17
    profiles: [ "with-db" ]
    container_name: yj-dev-db
    environment:
      POSTGRES_DB: ncafedb
      POSTGRES_USER: ncafe
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
